const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const { MongoMemoryServer } = require('mongodb-memory-server');

const app = express();
app.use(cors());
app.use(express.json());

// Post Schema
const postSchema = new mongoose.Schema({
  title: { type: String, required: true },
  content: { type: String, required: true },
  isPremium: { type: Boolean, default: false },
  seoScore: { type: Number, default: 0 }
});
const Post = mongoose.model('Post', postSchema);

// Seed Data
const seedPosts = [
  {
    title: 'Getting Started with Next.js App Router',
    content: '# Introduction to Next.js\n\nNext.js 13+ introduced the App Router, a paradigm shift in building React applications. It relies heavily on React Server Components (RSC) to improve performance by reducing the client-side JavaScript bundle size.\n\n## Server Side Rendering (SSR)\nWith SSR, pages are rendered on the server before being sent to the client. This is fantastic for SEO.',
    isPremium: false,
    seoScore: 92
  },
  {
    title: 'Advanced React Server Components (Premium)',
    content: '# Deep Dive into RSC\n\nReact Server Components allow you to write components that run exclusively on the server. This means they cannot use state (`useState`) or lifecycle methods (`useEffect`).\n\n## Why use them?\nBecause they never hydrate on the client, keeping your app fast and lean.',
    isPremium: true,
    seoScore: 98
  }
];

// Routes
app.get('/api/posts', async (req, res) => {
  try {
    const posts = await Post.find({}, '-__v');
    res.json(posts);
  } catch (error) {
    res.status(500).json({ message: 'Error fetching posts' });
  }
});

app.get('/api/posts/:id', async (req, res) => {
  try {
    const post = await Post.findById(req.params.id);
    if (!post) {
      return res.status(404).json({ message: 'Post not found' });
    }
    res.json(post);
  } catch (error) {
    res.status(500).json({ message: 'Error fetching post' });
  }
});

app.post('/api/ai/generate', (req, res) => {
  const { topic } = req.body;
  if (!topic) {
    return res.status(400).json({ message: 'Topic is required' });
  }
  
  const aiGeneratedContent = `# ${topic}\n\nHere is your AI generated content regarding ${topic}. This simulated response mimics an AI content generator.\n\n## Key Points\n- Point one about ${topic}\n- Point two about ${topic}\n\n*Generated by Mock AI Engine*`;
  
  res.json({ content: aiGeneratedContent });
});

// Initialization
let mongoServer;
const startServer = async () => {
  try {
    mongoServer = await MongoMemoryServer.create();
    const uri = mongoServer.getUri();
    await mongoose.connect(uri);
    console.log('Connected to In-Memory MongoDB');

    // Seed database
    await Post.deleteMany({});
    await Post.insertMany(seedPosts);
    console.log('Database seeded with dummy posts');

    const PORT = 5000;
    app.listen(PORT, () => {
      console.log(`Backend server running on http://localhost:${PORT}`);
    });
  } catch (error) {
    console.error('Failed to start server', error);
  }
};

startServer();
